language: generic
sudo: required
services:
  - docker

before_install:
  - ls
  - cd ./client
  - ls
  - docker build -t sergious79/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sergious79/react-test npm run test

after_success:
  - docker build -t sergious79/multi-client ./client
  - docker build -t sergious79/multi-nginx ./nginx
  - docker build -t sergious79/multi-server ./server
  - docker build -t sergious79/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sergious79/multi-client
  - docker push sergious79/multi-nginx
  - docker push sergious79/multi-server
  - docker push sergious79/multi-worker
